### ISSUE TITLE
Buenas a la hora de crear un link de pago me sale este error en el servidor 

### ISSUE THREAD

**Issue by Hacedor2003** [yosle/tropipayjs#6]
Error del servidor:
\node_modules\@yosle\tropipayjs\index.js:48
                    return new TropipayJSException(errorMessage, axiosResponse.status, axiosResponse.data.error);
                           ^
TropipayJSException [Error]: Invalid Parameter
    at handleExceptions (D:\Proyectos\Proyectos_VSC\Node.js\server-baraife\node_modules\@yosle\tropipayjs\index.js:48:28)
    at PaymentCard.create (D:\Proyectos\Proyectos_VSC\Node.js\server-baraife\node_modules\@yosle\tropipayjs\index.js:234:19)    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 400,
  error: {
    type: 'VALIDATION_ERROR',
    code: 'INVALID_PARAM',
    message: 'Invalid Parameter',
    details: [ [Object] ],
    i18n: 'Parámetros inválidos'
  }
}

payload link:

amount: 20
client: {name: "Bryan", lastName: "Espinosa", address: "Calle 4 entre line....a", phone: "585...",…}
address: "Calle 4 entre linea y calzada"
countryId: 1
countryIso: "CU"
email: "bryanlenier@gmail.com"
lastName: "Espinosa"
name: "Bryan"
phone: "58505864"
termsAndConditions: "true"
concept: "Baraife"
currency: "EUR"
description: "Son 20 productos"
directPayment: true
expirationDays: 1
favorite: false
lang: "es"
reasonId: 6
reference: "pago-2024-04-24-20"
serviceDate: "2024-04-24"
singleUse: true
urlFailed: "https://webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e"
urlNotification: "https://webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e"
urlSuccess: "https://webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e"

Verificacion:

reference: Joi.string().required().min(1),
	concept: Joi.string().required().min(1),
	favorite: Joi.boolean().required(),
	description: Joi.string().required().min(1),
	amount: Joi.number().required().min(11),
	currency: Joi.string().required().min(1),
	singleUse: Joi.boolean().required(),
	reasonId: Joi.number().required().min(0),
	expirationDays: Joi.number().required().min(0),
	lang: Joi.string().required().min(1).uppercase(),
	urlSuccess: Joi.string().min(1),
	urlFailed: Joi.string().min(1),
	urlNotification: Joi.string().min(1),
	serviceDate: Joi.string().min(1),
	client: Joi.object({
		name: Joi.string().required().min(1),
		lastName: Joi.string().required().min(1),
		address: Joi.string().required().min(1),
		phone: Joi.string().required().min(1),
		email: Joi.string().email().required(),
		countryId: Joi.number().required().min(1),
		countryIso: Joi.string().required().min(2).uppercase(),
		termsAndConditions: Joi.string().required().min(1),
	}),
	directPayment: Joi.boolean().required(),
	paymentMethods: Joi.array().items(Joi.string()),
	imageBase: Joi.string().base64().allow(""),

**Comment by Hacedor2003** [comment]
> Error del servidor: \node_modules@yosle\tropipayjs\index.js:48 return new TropipayJSException(errorMessage, axiosResponse.status, axiosResponse.data.error); ^ TropipayJSException [Error]: Invalid Parameter at handleExceptions (D:\Proyectos\Proyectos_VSC\Node.js\server-baraife\node_modules@yosle\tropipayjs\index.js:48:28) at PaymentCard.create (D:\Proyectos\Proyectos_VSC\Node.js\server-baraife\node_modules@yosle\tropipayjs\index.js:234:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) { code: 400, error: { type: 'VALIDATION_ERROR', code: 'INVALID_PARAM', message: 'Invalid Parameter', details: [ [Object] ], i18n: 'Parámetros inválidos' } }
> 
> payload link:
> 
> amount: 20 client: {name: "Bryan", lastName: "Espinosa", address: "Calle 4 entre linea y calzada", phone: "58505864",…} address: "Calle 4 entre linea y calzada" countryId: 1 countryIso: "CU" email: "[bryanlenier@gmail.com](mailto:bryanlenier@gmail.com)" lastName: "Espinosa" name: "Bryan" phone: "58505864" termsAndConditions: "true" concept: "Baraife" currency: "EUR" description: "Son 20 productos" directPayment: true expirationDays: 1 favorite: false lang: "es" reasonId: 6 reference: "pago-2024-04-24-20" serviceDate: "2024-04-24" singleUse: true urlFailed: "https://webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e" urlNotification: "https://webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e" urlSuccess: "https://webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e"
> 
> Verificacion:
> 
> reference: Joi.string().required().min(1), concept: Joi.string().required().min(1), favorite: Joi.boolean().required(), description: Joi.string().required().min(1), amount: Joi.number().required().min(11), currency: Joi.string().required().min(1), singleUse: Joi.boolean().required(), reasonId: Joi.number().required().min(0), expirationDays: Joi.number().required().min(0), lang: Joi.string().required().min(1).uppercase(), urlSuccess: Joi.string().min(1), urlFailed: Joi.string().min(1), urlNotification: Joi.string().min(1), serviceDate: Joi.string().min(1), client: Joi.object({ name: Joi.string().required().min(1), lastName: Joi.string().required().min(1), address: Joi.string().required().min(1), phone: Joi.string().required().min(1), email: Joi.string().email().required(), countryId: Joi.number().required().min(1), countryIso: Joi.string().required().min(2).uppercase(), termsAndConditions: Joi.string().required().min(1), }), directPayment: Joi.boolean().required(), paymentMethods: Joi.array().items(Joi.string()), imageBase: Joi.string().base64().allow(""),


Ya lo arregle era amount era muy poco

**Comment by yosle** [comment]
Primeramente gracias por crear el issue, así todos nos beneficiamos, por favor edita el mensaje anterior para asegurarte que no hay ninguna información personal suya. En este caso la respuesta de tropipay es  el error code invalid parameter lo cual no es muy útil para los efectos. Revisaré como podemos mejorar esto para una mejor gestión de errores

**Comment by Hacedor2003** [comment]
Buenas se puede mejorar este error

{
	"error": "Invalid Parameter"
}


{
	"payload": {
		"reference": "pago",
		"concept": "baraife",
		"favorite": "false",
		"amount": "2000",
		"currency": "EUR",
		"description": "Son productos",
		"singleUse": "true",
		"reasonId": 10,
		"expirationDays": 1,
		"lang": "es",
		"urlSuccess": "https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e",
		"urlFailed": "https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e",
		"urlNotification": "https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e",
		"serviceDate": "10",
		"directPayment": "true"
	}
}
